'use client';

import { useMemo, useState } from 'react';
import RealtimeDashboardV2 from './realtime-dashboard';

type PageProps = { page: string; onToast: (message: string) => void; onNavigate: (page: string) => void };

const pageTitles: Record<string, string> = {
  门店经营: '门店经营看板', 台桌实况: '台桌实况', 团购消费: '团购消费看板',
  会员数据: '会员基础看板', 线下赠券: '线下活动看板', 用户管理: '用户管理',
  角色管理: '角色管理', 菜单管理: '菜单管理', 审计日志: '审计日志', 系统管理: '系统管理',
};

const trendA = [28, 24, 21, 29, 25, 26, 34, 29, 25, 26, 27, 30, 29, 36, 37, 29, 27, 28, 32, 30, 35, 34];
const trendB = [36, 28, 25, 22, 29, 25, 26, 34, 29, 25, 26, 27, 29, 28, 36, 37, 27, 27, 28, 33, 30, 35];
const peopleA = [76, 92, 69, 82, 61, 71, 101, 75, 59, 52, 86, 102, 60, 77, 75, 67, 64, 64, 70, 69, 134, 111];
const peopleB = [36, 31, 29, 31, 26, 38, 42, 33, 39, 28, 40, 54, 28, 42, 39, 33, 30, 35, 46, 35, 56, 50];

function Help({ text }: { text: string }) {
  return <button className="mini-help" data-tip={text} aria-label={text}>i</button>;
}

function DashboardHeader({ title, onToast, live = false }: { title: string; onToast: (m: string) => void; live?: boolean }) {
  const [range, setRange] = useState('本月');
  const [region, setRegion] = useState('杭州一区');
  const [store, setStore] = useState('杭州滨江乐游城店');
  return <>
    <header className="topbar other-topbar">
      <div className="title-row"><h1>{title}</h1><div className="sync-status">{live ? '实时数据 30秒自动刷新　更新时间：21:03:53' : 'T+1数据　数据更新至2026-08-23 08:00'}<button aria-label="全屏" onClick={() => document.documentElement.requestFullscreen?.()}>⛶</button></div></div>
      <div className="filters">
        <label>大区：<select defaultValue="浙江大区"><option>浙江大区</option><option>总部直管区域</option></select></label>
        <label>区域：<select value={region} onChange={(e) => { setRegion(e.target.value); setStore(e.target.value === '杭州一区' ? '杭州滨江乐游城店' : '杭州金沙天街店'); }}><option>杭州一区</option><option>杭州二区</option><option>杭州三区</option></select></label>
        <label>门店：<select value={store} onChange={(e) => setStore(e.target.value)}><option>{region === '杭州一区' ? '杭州滨江乐游城店' : '杭州金沙天街店'}</option><option>杭州萧山金帝店</option><option>杭州滨江宝龙店</option></select></label>
        {!live && <div className="date-filter"><b>日期：</b>{['昨日','本月','本年','指定时间'].map(item => <button key={item} className={range === item ? 'active' : ''} onClick={() => { setRange(item); onToast(`已切换到${item}数据`); }}>{item}</button>)}</div>}
        {!live && <button className="refresh" onClick={() => onToast('数据已刷新')}>刷新 ↻</button>}
      </div>
    </header>
    <div className="manager-strip"><span>大区经理 <b>郑辉</b></span><span>区域经理 <b>暂无</b></span><span>店长 <b>朱家安</b></span><span>助教管理 <b>暂无</b></span><span>真实台桌 <b>50 台</b></span></div>
  </>;
}

function KpiCard({ icon, title, value, note, tone = 'blue' }: { icon: string; title: string; value: string; note?: string; tone?: string }) {
  return <article className={`kpi-card tone-${tone}`} tabIndex={0}><span className="kpi-icon">{icon}</span><div><small>{title}</small><strong>{value}</strong>{note && <em>{note}</em>}</div><Help text={`${title}为当前筛选范围内的汇总指标`} /></article>;
}

function TrendChart({ title, first = trendA, second = trendB, labels = ['营业额','环比营业额'], colors = ['#2372ef','#7c8ca4'] }: { title: string; first?: number[]; second?: number[]; labels?: string[]; colors?: string[] }) {
  const [hovered, setHovered] = useState<number | null>(null);
  const all = [...first, ...second]; const min = Math.min(...all) - 2; const max = Math.max(...all) + 2;
  const y = (v: number) => Number((92 - ((v - min) / (max - min)) * 80).toFixed(2));
  const line = (data: number[], color: string) => data.slice(0,-1).map((v,i) => {
    const x1 = (i/(data.length-1))*100, x2 = ((i+1)/(data.length-1))*100, y1=y(v), y2=y(data[i+1]);
    const falling = y2 > y1;
    return <i key={`${color}-${i}`} className="trend-segment" style={{left:`${x1.toFixed(2)}%`,top:`${Math.min(y1,y2)}%`,width:`${(x2-x1).toFixed(2)}%`,height:`${Math.max(1.5,Math.abs(y2-y1)).toFixed(2)}%`,background:`linear-gradient(to ${falling?'top':'bottom'} right, transparent calc(50% - 1.5px), ${color} calc(50% - 1.5px), ${color} calc(50% + 1.5px), transparent calc(50% + 1.5px))`}}/>;
  });
  return <section className="data-panel trend-card"><div className="data-title"><h2>{title}</h2><Help text={`悬浮折线数据点查看${title}明细`} /></div><div className="chart-key">{labels.map((l,i)=><span key={l}><i style={{background:colors[i]}} />{l}</span>)}</div><div className="trend-plot"><div className="chart-gridlines"><i/><i/><i/><i/></div>{line(first,colors[0])}{line(second,colors[1])}{first.map((v,i)=><button key={i} className="trend-hit" style={{left:`${((i/(first.length-1))*100).toFixed(2)}%`,top:`${y(v)}%`,borderColor:colors[0]}} onMouseEnter={()=>setHovered(i)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(i)} onBlur={()=>setHovered(null)} aria-label={`第${i+1}日 ${labels[0]} ${v}`}/>)}{hovered!==null&&<div className="trend-pop" style={{left:`${Math.min(90,Math.max(8,(hovered/(first.length-1))*100))}%`,top:`${Math.max(2,y(first[hovered])-26)}%`}}><b>08-{String(hovered+1).padStart(2,'0')}</b><span>{labels[0]} <strong>{first[hovered]}</strong></span><span>{labels[1]} <strong>{second[hovered]}</strong></span></div>}</div><div className="trend-axis">{['08-01','08-05','08-09','08-13','08-17','08-22'].map(x=><span key={x}>{x}</span>)}</div></section>;
}

function Donut({ value, label, colors = '#2372ef 0 32%,#10a77e 32% 90%,#c98912 90%' }: { value: string; label: string; colors?: string }) {
  return <div className="visual-donut" style={{background:`conic-gradient(${colors})`}}><i><b>{value}</b><small>{label}</small></i></div>;
}

function StoreDashboard({ onToast }: { onToast:(m:string)=>void }) {
  return <div className="page-pad">
    <div className="kpi-row four"><KpiCard icon="▣" title="总营收" value="¥487,185.63" note="较上月 ↓ 0.59%"/><KpiCard icon="▤" title="总客单量" value="2,088 单" note="线上834 · 线下1,254" tone="green"/><KpiCard icon="◴" title="平均客单时长" value="2.33 小时" note="达成率 116.5%" tone="amber"/><KpiCard icon="▰" title="平均单桌时长" value="4.42 小时" note="达成率 63.14%" tone="purple"/></div>
    <div className="store-layout"><section className="data-panel revenue-mix"><div className="data-title"><h2>营收构成</h2><Help text="台费、助教、商品及其他收入构成"/></div><Donut value="¥48.7万" label="总营收"/><ul><li><i className="c-blue"/>台费收入 <b>32%</b><span>¥157,916.53</span></li><li><i className="c-green"/>助教收入 <b>58%</b><span>¥279,941.10</span></li><li><i className="c-amber"/>商品收入 <b>10%</b><span>¥49,328.00</span></li><li><i className="c-purple"/>其他收入 <b>0%</b><span>¥0.00</span></li></ul></section><div className="store-trends"><TrendChart title="营收趋势图"/><TrendChart title="门店经营时段趋势图" first={peopleA} second={peopleB} labels={['客户消费人数','助教上课人数']} colors={['#2372ef','#0aa27a']}/></div></div>
    <div className="bottom-kpis"><button onClick={()=>onToast('挂账明细已展开')}><b>挂账</b><span>挂账数 <strong>3笔</strong></span><span>挂账金额 <strong>¥551.19</strong></span></button><button onClick={()=>onToast('会员卡明细已展开')}><b>会员卡</b><span>充值金额 <strong>¥38,884.00</strong></span><span>赠送金额 <strong>¥1,216.00</strong></span></button><button onClick={()=>onToast('到店数据已展开')}><b>客户到店数据</b><span>新增会员数 <strong>9</strong></span><span>会员账单数 <strong>364</strong></span><span>非会员账单数 <strong>2,991</strong></span></button></div>
  </div>;
}

const tableStates = [
  ...Array.from({length:37},(_,i)=>({name:String(i+7).padStart(2,'0'),state:i%7===0?'group':i%5===0?'booked':i%3===0?'busy':'empty'})),
];
const stateMeta:Record<string,{label:string;color:string}>={busy:{label:'开台',color:'#09a79c'},group:{label:'团购',color:'#ff6509'},booked:{label:'预订',color:'#2a7cb4'},empty:{label:'空闲',color:'#c4c9d1'}};
function TablesDashboard({onToast}:{onToast:(m:string)=>void}) {
  const [selected,setSelected]=useState<(typeof tableStates)[number]|null>(null);
  return <div className="page-pad table-page"><div className="table-main data-panel"><div className="table-section-title"><h2>区域台桌实况</h2><div>{Object.entries(stateMeta).map(([k,v])=><span key={k}><i style={{background:v.color}}/>{v.label}{k==='busy'?14:k==='group'?7:k==='booked'?4:25}</span>)}</div></div><h3>中八　（8/37台）　41%</h3><div className="table-grid">{tableStates.map((t,i)=><button key={t.name} className={`table-tile ${t.state}`} onClick={()=>setSelected(t)}><b>{t.name}</b>{t.state!=='empty'&&<><span>{`0${i%4}:${String((i*7)%60).padStart(2,'0')}`}</span>{(t.state==='busy'||t.state==='group')&&<small>♙×1　⌑</small>}<strong>{t.state==='booked'?'已预订':`¥${(i*23.75%330).toFixed(2)}`}</strong></>}</button>)}</div><h3>斯诺克　（4/6台）　67%</h3><div className="table-grid compact">{tableStates.slice(0,6).map((t,i)=><button key={i} className={`table-tile ${i===2?'empty':i===3?'booked':'busy'}`} onClick={()=>onToast(`斯诺克 ${String(i+1).padStart(2,'0')} 台详情`)}><b>{String(i+1).padStart(2,'0')}</b><span>00:{13+i*7}</span><strong>¥{43+i*32}.33</strong></button>)}</div></div><aside className="table-side"><section className="data-panel status-stat"><div className="data-title"><h2>台桌状态统计（共 50 台）</h2><Help text="当前门店台桌实时状态"/></div><Donut value="42%" label="开台率" colors="#09a79c 0 28%,#f2a000 28% 42%,#2b7eb7 42% 50%,#c7ccd3 50%"/><ul><li>开台 <b>14台　28%</b></li><li>团购 <b>7台　14%</b></li><li>暂停 <b>0台　0%</b></li><li>空闲 <b>25台　50%</b></li><li>预订 <b>4台　8%</b></li></ul></section><section className="data-panel status-stat"><div className="data-title"><h2>助教状态统计（共 70 人）</h2><Help text="助教当前上钟状态"/></div><Donut value="16%" label="上钟率" colors="#267db8 0 33%,#f2a000 33% 49%,#c7ccd3 49%"/><ul><li>空闲 <b>36人　51%</b></li><li>忙碌 <b>11人　16%</b></li><li>不在店 <b>23人　33%</b></li></ul></section></aside>{selected&&<div className="tile-detail"><button onClick={()=>setSelected(null)}>×</button><small>台桌 {selected.name}</small><h2>{stateMeta[selected.state].label}</h2><p>当前消费 ¥126.50 · 已进行 01:24</p><button onClick={()=>{setSelected(null);onToast('台桌详情已确认')}}>查看账单</button></div>}</div>;
}

function GroupBuyDashboard() {
  const hourly=[31,47,23,35,25,34,49,36,21,25,34,35,31,32,42,35,36,22,27,26,41,51];
  return <div className="page-pad"><div className="kpi-row four"><KpiCard icon="¥" title="核销金额" value="¥22,604.50" note="美团 68% · 抖音 32%"/><KpiCard icon="券" title="验券数量" value="738 张" note="57.73 元/张" tone="green"/><KpiCard icon="↗" title="团购衍生消费" value="¥9,060.32" note="台费20% · 商品费50% · 助教费30%" tone="purple"/><KpiCard icon="%" title="团购客单量占比" value="36.16%" note="团购消费431单" tone="amber"/></div><div className="two-charts"><TrendChart title="每小时团购核销券数" first={hourly} second={hourly.map((v,i)=>Math.max(5,v-12-i%5))} labels={['总核销券数','美团']} colors={['#2f80ed','#0aa49a']}/><section className="data-panel combo-chart"><div className="data-title"><h2>团购客单量（单）＋客单价（元/单）</h2><Help text="按小时展示团购与非团购表现"/></div><div className="combo-bars">{[55,52,62,103,64,231,114,18,0,0,28,20,25,32,34,52,54,57,45,47,52,48,61].map((v,i)=><button key={i} style={{height:`${Math.max(3,v/2.5)}%`}} aria-label={`${i}时客单量${v}`}><span>{v}</span></button>)}</div><div className="hour-axis"><span>0时</span><span>4时</span><span>8时</span><span>12时</span><span>16时</span><span>20时</span><span>23时</span></div></section></div><div className="triple-panels"><BarPanel title="衍生消费（每单）" values={[25,17,12,33,16,25,13,13,18,44,64,36,39,37,13,11,36,18,31,15,39,36]}/><BarPanel title="团购券核销（张数）" values={[31,47,23,35,25,34,49,36,21,25,34,35,31,32,42,35,36,22,27,26,41,51]} blue/><section className="data-panel top-store"><div className="data-title"><h2>团购客单TOP10门店</h2><Help text="按团购客单量排序"/></div><div className="table-head"><span>排名</span><span>门店名称</span><span>客单量</span><span>团购客单量</span></div><button><i>1</i><b>杭州滨江乐游城店</b><strong>2,558</strong><span>925　▰</span></button></section></div></div>;
}

function BarPanel({title,values,blue=false}:{title:string;values:number[];blue?:boolean}){return <section className="data-panel bar-panel"><div className="data-title"><h2>{title}</h2><Help text={`${title}每日趋势`}/></div><div className="bar-field">{values.map((v,i)=><button key={i} style={{height:`${Math.max(5,(v/Math.max(...values))*86)}%`,background:blue?'#3180ee':'#08a49c'}} aria-label={`08-${i+1} ${v}`}/>)}</div><div className="bar-axis"><span>08/01</span><span>08/07</span><span>08/13</span><span>08/19</span><span>08/22</span></div></section>}

function MemberDashboard({onToast}:{onToast:(m:string)=>void}){
  const lifecycle=[['活跃会员','0–30天有消费记录','79','6.04%','11,014','17.73%','78,786','43.20%','#347ef2'],['沉默会员 I','31–45天无消费记录','22','1.68%','399','0.64%','10,175','5.58%','#ff6b0a'],['沉默会员 II','46–50天无消费记录','8','0.61%','0','0.00%','2,703','1.48%','#25c0bd'],['沉默会员 III','超过50天无消费记录','1,197','91.58%','50,707','81.63%','90,703','49.74%','#7659f5']];
  return <div className="page-pad"><div className="kpi-row four"><KpiCard icon="▣" title="会员总数" value="1,307" note="新增：0人"/><KpiCard icon="♙" title="消费会员数" value="662" note="首销：0人" tone="green"/><KpiCard icon="◌" title="会员客单占比" value="—" tone="purple"/><KpiCard icon="▤" title="会员客单价" value="320 元/单" tone="amber"/></div><div className="member-main"><section className="data-panel member-pyramid"><div className="data-title"><h2>会员等级分布</h2><Help text="按当前会员等级展示人数占比"/></div><button className="tier diamond" onClick={()=>onToast('钻石会员 1人')}>钻石会员</button><button className="tier platinum" onClick={()=>onToast('铂金会员 4人')}>铂金会员</button><button className="tier gold" onClick={()=>onToast('黄金会员 182人')}>黄金会员</button><button className="tier silver" onClick={()=>onToast('白银会员 1,120人')}>白银会员</button></section><section className="data-panel lifecycle"><div className="data-title"><h2>会员生命周期分析</h2><Help text="按最近消费时间划分会员活跃度"/></div><div className="life-head"><span>生命周期</span><span>数量</span><span>数量占比</span><span>会员余额</span><span>余额占比</span><span>积分余额</span><span>积分占比</span></div>{lifecycle.map(row=><button key={row[0]} onClick={()=>onToast(`${row[0]}详情已展开`)}><span><i style={{background:row[8]}}>♙</i><b>{row[0]}</b><small>{row[1]}</small></span>{row.slice(2,8).map((v,i)=><em key={i}>{v}{[1,3,5].includes(i)&&<u style={{width:v,background:row[8]}}/>}</em>)}</button>)}</section></div><div className="member-bottom"><div className="member-ledger">{[['储值','余额结存：458,513','累计充值：74,607,675','新增充值：160,000'],['消费','累计消费：82,418,791','新增消费：230,432',''],['积分','积分结存：6,589,923','累计积分：14,537,417','新增积分：289,735']].map((x,i)=><button key={x[0]} onClick={()=>onToast(`${x[0]}数据已展开`)}><span className={`tone-${i===0?'blue':i===1?'green':'amber'}`}>{i===0?'▣':i===1?'⌑':'☆'}</span><b>{x[0]}</b><div><small>{x[1]}</small><small>{x[2]}</small><small>{x[3]}</small></div></button>)}</div><BarPanel title="会员拉新＋首销＋首充人数（近7天趋势）" values={[1,1,1,0,1,0,0,0,1,1,1,1,1,1,0,2,1,1,0,0,1,1]}/></div></div>;
}

function CouponDashboard(){return <div className="page-pad"><div className="kpi-row four"><KpiCard icon="◇" title="线下送券总数" value="100 张" tone="green"/><KpiCard icon="✓" title="总核销张数" value="10 张" tone="green"/><KpiCard icon="%" title="优惠券核销率" value="10.00%"/><KpiCard icon="▣" title="优惠券衍生营收总额" value="0.00 元" tone="purple"/></div><div className="coupon-main"><TrendChart title="线下活动送券情况折线图" first={[0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0]} second={Array(22).fill(0)} labels={['员工转赠券','消费送券']} colors={['#6d62f5','#2d80ed']}/><section className="data-panel sankey"><div className="data-title"><h2>员工转赠券桑基图分析</h2><Help text="展示优惠券从投放到转赠、使用的流向"/></div><div className="flow"><button className="flow-source"><b>已投放</b><span>员工转赠券</span><strong>100 张</strong><small>100.00%</small></button><i className="flow-line l1"/><i className="flow-line l2"/><i className="flow-line l3"/><button className="flow-node green"><b>未转赠</b><span>78 张</span><small>78.00%</small></button><button className="flow-node blue"><b>已转赠</b><span>22 张</span><small>22.00%</small></button><button className="flow-node orange"><b>已废除</b><span>0 张</span><small>0.00%</small></button><button className="flow-end used"><b>已使用</b><span>10 张</span><small>45.45%</small></button><button className="flow-end unused"><b>未使用</b><span>12 张</span><small>54.55%</small></button></div></section></div><div className="coupon-bottom"><section className="data-panel empty-chart"><div className="data-title"><h2>优惠券首单客户、转化客户分析</h2><Help text="客户转化数据"/></div><div className="empty-baseline">0　0　　　0　0　　　0　0　　　0　0</div></section><section className="data-panel coupon-ratio"><div className="data-title"><h2>优惠券有无衍生消费客户量分析</h2><Help text="有衍生消费与无衍生消费客户量占比"/></div><strong>总客户量：<b>4</b> 人</strong><div><span>100.00%</span></div><small>有衍生消费客户量 <b>0 人</b>　　无衍生消费客户量 <b>4 人</b></small></section><BarPanel title="转赠券去向客群分层" values={[7,0]} blue/></div></div>}

function RealtimeDashboard({onToast,onBack}:{onToast:(m:string)=>void;onBack:()=>void}){
  return <section className="realtime-board"><header><div className="rt-actions"><button onClick={()=>onToast('已切换全国数据')}>⌾　全国　▼</button><button onClick={onBack}>← 返回业务看板</button></div><h1><span className="brand-mark"><i>K</i></span> KK实时经营大屏</h1><div><b>2026-08-20　19:36:23</b><small>↻ 每 30s 刷新</small></div></header><div className="rt-layout"><aside><section><h2>区域目标进度</h2>{[['浙江大区','81%'],['苏皖大区','60%'],['总部直管','91%']].map((x,i)=><button key={x[0]} onClick={()=>onToast(`${x[0]}目标详情`)}><b>{x[0]}</b><span>¥ 5829.3万</span><strong>{x[1]}</strong><i style={{width:x[1],background:i===1?'#ff6d12':'#50c99e'}}/></button>)}</section><section><h2>门店目标达成情况</h2><div className="rt-donut"><b>242</b><small>门店总数</small></div><p>达标 ≥100%　<b>128 家</b></p><p>正常 90–99%　<b>96 家</b></p><p className="orange">滞后 ＜90%　<b>18 家</b></p></section><section><h2>门店目标完成榜</h2>{['镇江悦然广场店','苏州平江万达店','杭州萧山金帝店','杭州滨江宝龙店'].map((s,i)=><p key={s}>{i+1}　{s}<b>{65+i*5}%</b></p>)}</section></aside><main><div className="rt-goals"><section><div className="goal-ring green">50%</div><span><b>年度目标</b><strong>¥ 58239.3 万</strong><small>目标金额　¥ 12000 万</small></span></section><section><div className="goal-ring orange">50%</div><span><b>8月目标</b><strong>¥ 58239.3 万</strong><small>目标金额　¥ 12000 万</small></span></section></div><section className="map-panel"><div className="rt-title">区域及门店地图</div><div className="china-map"><div className="map-shape"/><button style={{left:'72%',top:'56%'}}>沪</button><button style={{left:'68%',top:'61%'}}>浙</button><button style={{left:'62%',top:'67%'}}>湘</button><button style={{left:'52%',top:'55%'}}>川</button><button style={{left:'59%',top:'49%'}}>渝</button><button style={{left:'74%',top:'69%'}}>闽</button><button style={{left:'67%',top:'76%'}}>粤</button><button style={{left:'58%',top:'80%'}}>桂</button></div><div className="map-stats"><span>大区 <b>8</b></span><span>区域 <b>68</b></span><span>门店 <b>178</b></span><span>筹备中 <b>8</b></span><span>已闭店 <b>13</b></span></div><footer><span>最佳区域　<b>华东 108.6%</b></span><span>最大缺口　<b>华北 −214万</b></span><span>重点关注　<b>西南 84.7%</b></span></footer></section></main><aside className="rt-right"><section><h2>总营业额月度走势</h2><div className="rt-spark">╱╱╱╱⌁⌁╱╱</div><small>— 实际营收　-- 目标营收</small></section><section><h2>营业额业务构成</h2><Donut value="1.06亿" label="台费合计" colors="#57c79e 0 75%,#4ca6c8 75% 90%,#fb8b2f 90%"/><p>台费　<b>¥8491.23万</b></p><p>助教　<b>¥1491.23万</b></p><p>商品　<b>¥491.23万</b></p></section><section><h2>客单量　<b>118单</b></h2><div className="rt-mini-line">⌁⌁⌁⌁⌁⌁</div><h2>平均客单时长　<b>1.8小时</b></h2><div className="rt-mini-line">⌁⌁⌁⌁⌁</div></section></aside></div></section>
}

function SystemDashboard({page,onToast}:{page:string;onToast:(m:string)=>void}){
  const rows=page==='用户管理'?[['admin','超级管理员','正常','2026-08-24 09:12'],['zhangwei','区域经理','正常','2026-08-23 18:46'],['lina','门店店长','正常','2026-08-23 16:08'],['guest','数据访客','停用','2026-08-18 11:32']]:page==='角色管理'?[['超级管理员','全部权限','12','启用'],['区域经理','区域数据','26','启用'],['门店店长','门店数据','178','启用'],['数据访客','只读权限','8','停用']]:page==='菜单管理'?[['实时大屏','/realtime','一级菜单','显示'],['门店经营','/analysis/store','一级菜单','显示'],['会员营销','/analysis/member','一级菜单','显示'],['系统管理','/system','一级菜单','显示']]:[['admin','登录系统','杭州滨江乐游城店','成功'],['zhangwei','导出经营报表','浙江大区','成功'],['admin','修改角色权限','超级管理员','成功'],['guest','访问会员数据','杭州一区','拒绝']];
  const [query,setQuery]=useState(''); const filtered=rows.filter(r=>r.join('').includes(query));
  return <div className="page-pad system-page"><div className="kpi-row four"><KpiCard icon="♙" title="用户总数" value="226" note="今日活跃 87"/><KpiCard icon="⌘" title="角色数量" value="12" note="启用 11" tone="green"/><KpiCard icon="☷" title="菜单节点" value="46" note="前台页面 7" tone="purple"/><KpiCard icon="✓" title="今日操作" value="1,286" note="成功率 99.8%" tone="amber"/></div><section className="data-panel system-table"><div className="system-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`搜索${page.replace('管理','')}`}/><button onClick={()=>onToast(`已新建${page.replace('管理','')}`)}>＋ 新建</button><button onClick={()=>onToast('列表已刷新')}>↻ 刷新</button></div><div className="sys-head"><span>名称/账号</span><span>类型/操作</span><span>范围/状态</span><span>最后更新</span><span>操作</span></div>{filtered.map((row,i)=><div className="sys-row" key={i}>{row.map((v,j)=><span key={j}>{v}</span>)}<span><button onClick={()=>onToast(`正在编辑 ${row[0]}`)}>编辑</button><button onClick={()=>onToast(`已查看 ${row[0]} 详情`)}>详情</button></span></div>)}</section></div>
}

export default function DashboardPage({page,onToast,onNavigate}:PageProps){
  if(page==='实时大屏') return <section className="workspace other-workspace realtime-workspace"><RealtimeDashboardV2 onToast={onToast} onBack={()=>onNavigate('门店经营')}/></section>;
  const content = page==='门店经营'?<StoreDashboard onToast={onToast}/>:page==='台桌实况'?<TablesDashboard onToast={onToast}/>:page==='团购消费'?<GroupBuyDashboard/>:page==='会员数据'?<MemberDashboard onToast={onToast}/>:page==='线下赠券'?<CouponDashboard/>:<SystemDashboard page={page} onToast={onToast}/>;
  return <section className="workspace other-workspace"><DashboardHeader title={pageTitles[page]||page} onToast={onToast} live={page==='台桌实况'}/>{content}</section>;
}
